package com.example.ui.theme

object Localization {

    private val enStrings = mapOf(
        "app_title" to "AyuCare: Elderly Med-Alarm",
        "patient_view" to "Patient Screen (High Contrast)",
        "caregiver_view" to "Caregiver Setup & Logs",
        "patient_name" to "Patient Name",
        "patient_age" to "Patient Age",
        "emergency_phone" to "Emergency Contact Number",
        "save_profile" to "Save Patient Profile",
        "settings_permissions" to "Caregiver Setup & System Permissions",
        "perm_instructions" to "Configure standard system permissions below to ensure alarms bypass DND/silent mode, launch full-screen, and survive background memory kills.",
        "active_schedules" to "Caregiver Medication Schedules",
        "dosage" to "Dosage (e.g. 1 Tablet, 5ml)",
        "time" to "Remind Time",
        "voice_phrase" to "Voice Phrase Confirmation Word",
        "voice_phrase_hint" to "(e.g., 'taken', 'kheyechi', 'le liya')",
        "add_med_button" to "Add & Schedule Alert",
        "sync_dashboard" to "Caregiver Synchronization Dashboard",
        "sync_status_label" to "Cloud Sync Status:",
        "sync" to "Sync Now",
        "instant_alerts" to "Caregiver Instant Missed Dose Logs",
        "no_alerts" to "No missed dose alerts. Patient is adhering perfectly!",
        "adherence_history" to "Medication Logs & Adherence History",
        "logged_at" to "Scheduled:",
        "taken_at" to "Marked Taken:",
        "status_taken" to "TAKEN",
        "status_pending" to "PENDING",
        "status_missed" to "MISSED",
        "confirmed_via" to "Verified via:",
        "delete_med_confirm" to "Delete Schedule",
        "active_alarm_status" to "ATTENTION: MEDICINE ALERT!",
        "dosage_alert" to "Dosage To Take:",
        "voice_confirm_prompt" to "Press and Say Word:",
        "voice_say" to "or say",
        "voice_listening" to "LISTENING... PLEASE SPEAK NOW",
        "voice_matching_success" to "Voice Matched! Marked taken.",
        "voice_simulate_btn" to "Simulator Voice confirmation",
        "manual_confirm_btn" to "YES, I HAVE TAKEN MY MEDICINE",
        "years" to "years old",
        "active_reminder_count" to "Active Scheds:",
        "language_select" to "Preferred Language:",
        "permissions_btn_post" to "Notification Permission",
        "permissions_btn_alarm" to "Schedule Exact Alarms",
        "permissions_btn_overlay" to "Draw Over Lockscreen (Overlay)",
        "state_allowed" to "ALLOWED",
        "state_configure" to "CONFIGURE",
        "bengali_label" to "বাংলা (Bengali)",
        "hindi_label" to "हिन्दी (Hindi)",
        "english_label" to "English",
        "caregiver_control_title" to "Caregiver Administration Settings",
        "sos_hold_prompt" to "HOLD 3 SEC TO CALL CAREGIVER"
    )

    private val bnStrings = mapOf(
        "app_title" to "আয়ু-কেয়ার: প্রবীণ মেড-অ্যালার্ম",
        "patient_view" to "রোগীর স্ক্রীন (উচ্চ বৈপরীত্য)",
        "caregiver_view" to "কেয়ারগিভার সেটআপ ও লগ্স",
        "patient_name" to "রোগীর নাম",
        "patient_age" to "রোগীর বয়স",
        "emergency_phone" to "জরুরী যোগাযোগের নম্বর",
        "save_profile" to "প্রোফাইল সংরক্ষণ করুন",
        "settings_permissions" to "কেয়ারগিভার সেটআপ ও সিস্টেম অনুমতিসমূহ",
        "perm_instructions" to "অ্যালার্ম সাইলেন্ট মোড এড়াতে এবং ব্যাকগ্রাউন্ড মেমোরি কিলিং থেকে রক্ষা পেতে সিস্টেমের সেটিংসগুলি নিচে কনফিগার করুন।",
        "active_schedules" to "কেয়ারগিভার ঔষধের তালিকা",
        "dosage" to "ডোজ (যেমন ১টি ট্যাবলেট, ৫ এমএল)",
        "time" to "স্মরণ করার সময়",
        "voice_phrase" to "ভয়েস নিশ্চিতকরণ কাস্টম শব্দ",
        "voice_phrase_hint" to "(যেমন 'taken', 'kheyechi', 'le liya')",
        "add_med_button" to "তালিকায় যোগ করুন ও অ্যালার্ম সেট করুন",
        "sync_dashboard" to "কেয়ারগিভার ক্লাউড সিঙ্ক্রোনাইজেশন ড্যাশবোর্ড",
        "sync_status_label" to "আজকের ক্লাউড সিঙ্ক স্থিতি:",
        "sync" to "সিঙ্ক করুন",
        "instant_alerts" to "কেয়ারগিভার ইনস্ট্যান্ট মিস্ড ডোজ নোটিফিকেশন",
        "no_alerts" to "কোনো মিসড ডোজ অ্যালার্ট নেই। রোগী চমৎকারভাবে ঔষধ নিচ্ছেন!",
        "adherence_history" to "ঔষধ খাওয়ার ইতিহাস ও প্রমাণ তালিকা",
        "logged_at" to "নির্ধারিত সময়:",
        "taken_at" to "নেওয়ার সময়:",
        "status_taken" to "গৃহীত হয়েছে (TAKEN)",
        "status_pending" to "অপেক্ষমান (PENDING)",
        "status_missed" to "মিস হয়েছে (MISSED)",
        "confirmed_via" to "যাচাইকরণ মাধ্যম:",
        "delete_med_confirm" to "তালিকা থেকে মুছুন",
        "active_alarm_status" to "মনোযোগ দিন: ঔষধ খাওয়ার সময় হয়েছে!",
        "dosage_alert" to "গ্রহণের পরিমাণ:",
        "voice_confirm_prompt" to "টিপুন এবং শব্দটি জোড়ে বলুন:",
        "voice_say" to "অথবা বলুন",
        "voice_listening" to "শুনছি... অনুগ্রহ করে এখন স্পষ্ট বলুন",
        "voice_matching_success" to "কণ্ঠস্বর মিলেছে! ঔষধ নেওয়া হয়েছে হিসেবে চিহ্নিত করা হল।",
        "voice_simulate_btn" to "ভয়েস সিমুলেটর দিয়ে নিশ্চিত করুন",
        "manual_confirm_btn" to "হ্যাঁ, আমি আমার ঔষধ খেয়েছি",
        "years" to "বছর বয়স",
        "active_reminder_count" to "সক্রিয় অ্যালার্ম সংখ্যা:",
        "language_select" to "পছন্দসই ভাষা:",
        "permissions_btn_post" to "নোটিফিকেশন অনুমতি",
        "permissions_btn_alarm" to "সঠিক সময় অ্যালার্ম অনুমতি",
        "permissions_btn_overlay" to "লকস্ক্রিনে দেখানোর অনুমতি (ওভারলে)",
        "state_allowed" to "অনুমোদিত",
        "state_configure" to "সেটিংস চালু করুন",
        "bengali_label" to "বাংলা",
        "hindi_label" to "हिन्दी",
        "english_label" to "English",
        "caregiver_control_title" to "কেয়ারগিভার নিয়ন্ত্রণ কেন্দ্র",
        "sos_hold_prompt" to "কেয়ারগিভারকে কল করতে ৩ সেকেন্ড চেপে রাখুন"
    )

    private val hiStrings = mapOf(
        "app_title" to "आयु-केयर: बुजुर्ग मेड-अलार्म",
        "patient_view" to "रोगी स्क्रीन (उच्च कंट्रास्ट)",
        "caregiver_view" to "केयरगिवर सेटअप और लॉग्स",
        "patient_name" to "मरीज का नाम",
        "patient_age" to "मरीज की उम्र",
        "emergency_phone" to "आपातकालीन संपर्क नंबर",
        "save_profile" to "प्रोफ़ाइल सुरक्षित करें",
        "settings_permissions" to "केयरगिवर सेटअप और सिस्टम अनुमतियां",
        "perm_instructions" to "अलार्म को साइलेंट मोड से बचाने और बैकग्राउंड किलिंग से सुरक्षित रखने के लिए नीचे सिस्टम अनुमतियां सेट करें।",
        "active_schedules" to "केयरगिवर दवा समय सूची",
        "dosage" to "खुराक (जैसे 1 गोली, 5ml)",
        "time" to "अलार्म का समय",
        "voice_phrase" to "वॉइस कन्फर्मेशन शब्द",
        "voice_phrase_hint" to "(जैसे 'taken', 'kheyechi', 'le liya')",
        "add_med_button" to "दवा जोड़ें और अलार्म लगाएं",
        "sync_dashboard" to "केयरगिवर समतुल्य क्लाउड डैशबोर्ड",
        "sync_status_label" to "क्लाउड सिंक स्थिति:",
        "sync" to "सिंक करें",
        "instant_alerts" to "केयरगिवर इंस्टेंट मिस खुराक अलर्ट",
        "no_alerts" to "कोई छूटी हुई खुराक नहीं। मरीज दवाओं का पालन अच्छे से कर रहे हैं!",
        "adherence_history" to "दवा रिकॉर्ड और अनुपालन इतिहास",
        "logged_at" to "निर्धारित समय:",
        "taken_at" to "लेने का समय:",
        "status_taken" to "लिया गया है (TAKEN)",
        "status_pending" to "लंबित (PENDING)",
        "status_missed" to "छूट गया (MISSED)",
        "confirmed_via" to "सत्यापन विधि:",
        "delete_med_confirm" to "सूची से हटाएं",
        "active_alarm_status" to "ध्यान दें: दवा का समय हो गया है!",
        "dosage_alert" to "ले जाने वाली खुराक:",
        "voice_confirm_prompt" to "दबाएं और शब्द बोलें:",
        "voice_say" to "या बोलें",
        "voice_listening" to "सुन रहा हूँ... कृपया अभी कहें",
        "voice_matching_success" to "आवाज मिल गई! दवा दर्ज की गई।",
        "voice_simulate_btn" to "आवाज सिम्युलेटर के साथ पुष्टि करें",
        "manual_confirm_btn" to "हां, मैंने अपनी दवा ले ली है",
        "years" to "वर्ष उम्र",
        "active_reminder_count" to "सक्रिय अलार्म:",
        "language_select" to "पसंदीदा भाषा:",
        "permissions_btn_post" to "अधिसूचना अनुमति",
        "permissions_btn_alarm" to "सटीक अलार्म अनुमति",
        "permissions_btn_overlay" to "लॉक स्क्रीन ओवरले अनुमति",
        "state_allowed" to "स्वीकृत",
        "state_configure" to "चालू करें",
        "bengali_label" to "বাংলা",
        "hindi_label" to "हिन्दी",
        "english_label" to "English",
        "caregiver_control_title" to "केयरगिवर नियंत्रण केंद्र",
        "sos_hold_prompt" to "केयरगिवर को कॉल करने के लिए 3 सेकंड दबाकर रखें"
    )

    fun getString(key: String, lang: String): String {
        val dict = when (lang.uppercase()) {
            "BN" -> bnStrings
            "HI" -> hiStrings
            else -> enStrings
        }
        return dict[key] ?: enStrings[key] ?: key
    }
}
